INSERT INTO `USERS` (NAME,EMAIL,USER_NAME,PASSWORD) VALUES ('Souvik' , 'ss@gmail.com' , 'ss' , 'user');
INSERT INTO `USERS` (NAME,EMAIL,USER_NAME,PASSWORD) VALUES ('ADMIN' , 'admin@admin.com' , 'admin' , 'admin');

INSERT INTO `ROLE` (ROLE) VALUES ('ROLE_USER');
INSERT INTO `ROLE` (ROLE) VALUES ('ROLE_ADMIN');
INSERT INTO `ROLE` (ROLE) VALUES ('ROLE_GUEST');


INSERT INTO `DATA` (TYPE) VALUES (' Type 1');
INSERT INTO `DATA` (TYPE) VALUES (' Type 2');
INSERT INTO `DATA` (TYPE) VALUES (' Type 3');
INSERT INTO `DATA` (TYPE) VALUES (' Type 4');

INSERT INTO `USER_ROLES` (USER_ID,ROLE_ID) VALUES (1 , 1);
INSERT INTO `USER_ROLES` (USER_ID,ROLE_ID) VALUES (1 , 2);
INSERT INTO `USER_ROLES` (USER_ID,ROLE_ID) VALUES (1 , 3);
